name: Create Tag on Merge

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Tag
        run: |
          # Get the latest tag from the main branch
          latest_tag=$(git describe --tags --abbrev=0)

          # Extract the tag version number
          tag_version=$(echo "$latest_tag" | grep -oP '\d+\.\d+\.\d+')

          # Increment the minor version number
          IFS='.' read -r major minor patch <<< "$tag_version"
          new_minor=$((minor + 1))
          new_tag_version="$major.$new_minor.$patch"

          # Create the new tag and push it
          git tag -a "$new_tag_version" -m "Automated tag creation on branch merge"
          git push origin "$new_tag_version"

      - name: Clean up
        run: |
          git fetch --tags
          git tag -d "$new_tag_version"
          git push origin ":refs/tags/$new_tag_version"
