on:
  release:
    types: [created]

jobs:

  trigger-jitpack-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: trigger build on jitpack
        run: |
          curl --request GET "https://jitpack.io/api/builds/settle-finance/java-integration-sdk/${{ github.event.release.tag_name }}"